on: [push, pull_request]
name: Static analysis
jobs:
  phpstan:
    name: PHPStan
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run
